# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SinaMenuViewExample' do

pod 'XHRealTimeBlur'
pod 'pop'

end

target 'SinaMenuViewExampleTests' do

end

